[package]
name = "WebVPN"
version = "0.1.0"
edition = "2018"
authors = ["Salem Yaslem <s@sy.sa>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webrtc = "0.3.1"
tokio = { version = "1.13.0", features = ["full"] }
env_logger = "0.9.0"
clap = "2.33.3"
hyper = { version = "0.14.14", features = ["full"] }
signal = {path = "src/signal" }
tokio-util = "0.6.9"
anyhow = "1.0.45"
chrono = "0.4.19"
log = "0.4.14"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.70"
bytes = "1.1.0"
lazy_static = "1.4.0"
rand = "0.8.4"
tun = { version = "0.5", features = ["async"] }